### ISSUE TITLE
Suggestion: Jackal Launch option

### ISSUE THREAD

**Issue by Pirate144** [jordanrye/nexus-control-options#1]
Here is a video about it. https://www.youtube.com/watch?v=BsFiWgqBnPA

Any thoughts about including an option for it?

**Comment by jordanrye** [comment]
I don't think this would be ToS-compliant based on the following policy:

> You cannot use macros to create skill chains in any competitive environment, including PvP, WvW, open world activities, races, etc. [[Source](https://help.guildwars2.com/hc/en-us/articles/360013762153-Policy-Macros-and-Macro-Use)]

Happy to continue the discussion on the [Nexus Discord](https://discord.gg/Mvk7W7gjE4).
